////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#include <wx/button.h>
#include <wx/sizer.h>

#include "../imports/crafter_base.hpp"
#include "../imports/form_base.h"
#include "../imports/import_crafter_base.h"
#include "../imports/import_form_base.h"

#include "import_test_base.h"

bool ImportTest::Create(wxWindow* parent, wxWindowID id, const wxString& title,
        const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{
    if (!wxDialog::Create(parent, id, title, pos, size, style, name))
        return false;

    auto dlg_sizer = new wxBoxSizer(wxVERTICAL);

    m_splitter = new wxSplitterWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D);
    m_splitter->SetSashGravity(0.0);
    m_splitter->SetMinimumPaneSize(150);
    dlg_sizer->Add(m_splitter, wxSizerFlags().Border(wxALL));

    m_panel_import_fb = new ImportFormBuilder(m_splitter, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);

    m_panel_formbuilder = new FormBuilderBase(m_splitter, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_splitter->SplitVertically(m_panel_import_fb, m_panel_formbuilder);

    m_splitter_2 = new wxSplitterWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxSP_3D);
    m_splitter_2->SetSashGravity(0.0);
    m_splitter_2->SetMinimumPaneSize(150);
    dlg_sizer->Add(m_splitter_2, wxSizerFlags().Border(wxALL));

    m_panel_import_crafter = new ImportCrafterBase(m_splitter_2, wxID_ANY, wxDefaultPosition, wxDefaultSize,
        wxTAB_TRAVERSAL);

    m_panel_crafter = new CrafterBase(m_splitter_2, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_splitter_2->SplitVertically(m_panel_import_crafter, m_panel_crafter);

    auto stdBtn = CreateStdDialogButtonSizer(wxOK|wxCANCEL);
    dlg_sizer->Add(CreateSeparatedSizer(stdBtn), wxSizerFlags().Expand().Border(wxALL));

    SetSizerAndFit(dlg_sizer);
    Centre(wxBOTH);

    // Event handlers
    Bind(wxEVT_INIT_DIALOG, &ImportTest::OnInit, this);

    return true;
}
