////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <wx/gdicmn.h>

#include <wx/bmpbndl.h>

wxImage wxueImage(const unsigned char* data, size_t size_data);

namespace wxue_img
{
    wxBitmapBundle bundle_wiztest_png();
    wxBitmapBundle bundle_wiztest2_png();

    extern const unsigned char wiztest2_png[6797];
    extern const unsigned char wiztest_png[1239];
}
