////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <wx/colour.h>
#include <wx/combobox.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/gdicmn.h>
#include <wx/radiobut.h>
#include <wx/settings.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>

class PythonDlgBase : public wxDialog
{
public:
    PythonDlgBase() {}
    PythonDlgBase(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Hello Python Dialog!",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Hello Python Dialog!",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr);

protected:

    // Event handlers

    void OnInit(wxInitDialogEvent& event);
    void OnText(wxCommandEvent& event);

    // Class member variables

    wxComboBox* m_comboBox;
    wxRadioButton* m_radioBtn;
    wxStaticText* m_staticText2;
    wxTextCtrl* m_textCtrl;
};
