///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#include <wx/bitmap.h>
#include <wx/icon.h>
#include <wx/image.h>

#include "form_toolbar_base.h"

#include <wx/mstream.h>  // memory stream classes

// Convert a data array into a wxImage
wxImage wxueImage(const unsigned char* data, size_t size_data);

namespace wxue_img
{
    extern const unsigned char english_png[541];
    extern const unsigned char french_png[252];
    extern const unsigned char japanese_png[377];
}

MyToolBarBase::MyToolBarBase(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style,
    const wxString& name) : wxToolBar(parent, id, pos, size, style, name)
{

    if (!wxImage::FindHandler(wxBITMAP_TYPE_PNG))
        wxImage::AddHandler(new wxPNGHandler);

    AddTool(wxID_ANY, wxEmptyString,
        wxueImage(wxue_img::english_png, sizeof(wxue_img::english_png)), wxEmptyString, wxITEM_RADIO);

    AddTool(wxID_ANY, wxEmptyString,
        wxueImage(wxue_img::french_png, sizeof(wxue_img::french_png)), wxEmptyString, wxITEM_RADIO);

    AddTool(wxID_ANY, wxEmptyString,
        wxueImage(wxue_img::japanese_png, sizeof(wxue_img::japanese_png)), wxEmptyString, wxITEM_RADIO);

    m_comboBox = new wxComboBox(this, wxID_ANY);
    m_comboBox->Append("English");
    m_comboBox->Append("French");
    m_comboBox->Append("Japanese");
    m_comboBox->SetStringSelection("English");
    AddControl(m_comboBox);

    Realize();
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
