# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (sdi_generated_code

    # Non-base classes
    ${CMAKE_CURRENT_LIST_DIR}/cpp/bitmaps_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/booktest_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/commonctrls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/data_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/generic_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/images.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/mainframe.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/popupwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/propsheet_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/python_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/testformpanel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/wizard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/wxue_data.cpp

    # Base classes
    ${CMAKE_CURRENT_LIST_DIR}/cpp/dlgissue_956.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/dlgissue_960.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/form_aui_toolbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/form_menu_bar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/form_popup_menu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/form_ribbonbar_gallery.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/form_ribbonbar_tool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/form_toolbar_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/maintestdialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/tools_dlg.cpp

)

set (sdi_generated_code_data

    ${CMAKE_CURRENT_LIST_DIR}/../xrc/python_dlg.xrc

)
