###############################################################################
# Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# Do not edit any code above the "End of generated code" comment block.
# Any changes before that block will be lost if it is re-generated!
###############################################################################

"""PropSheetBase class generated by wxUiEditor."""

import wx
import wx.adv

import images
import zlib
import base64

class PropSheetBase(wx.adv.PropertySheetDialog):
    def __init__(self, parent, id=wx.ID_ANY, title="wxPropertySheetDialog",
                pos=wx.DefaultPosition, size=wx.DefaultSize,
                style=wx.DEFAULT_DIALOG_STYLE, name=wx.DialogNameStr):
        wx.adv.PropertySheetDialog.__init__(self)
        self.SetSheetStyle(wx.adv.PROPSHEET_NOTEBOOK)
        self.SetSheetInnerBorder(20)

        if not self.Create(parent, id, title, pos, size, style, name):
            return
        self.CreateButtons(wx.OK|wx.CANCEL)

        page1 = wx.Panel(self.GetBookCtrl(), wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize,
            wx.TAB_TRAVERSAL)
        self.GetBookCtrl().AddPage(page1, "Page 1")

        page_sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.staticText1 = wx.StaticText(page1, wx.ID_ANY,
            "TODO: replace this control with something more useful...")
        self.staticText1.Wrap(200)
        page_sizer_1.Add(self.staticText1, wx.SizerFlags().Border(wx.ALL))
        page1.SetSizerAndFit(page_sizer_1)

        page2 = wx.Panel(self.GetBookCtrl(), wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize,
            wx.TAB_TRAVERSAL)
        self.GetBookCtrl().AddPage(page2, "Page 2")

        page_sizer_2 = wx.BoxSizer(wx.VERTICAL)

        self.staticText2 = wx.StaticText(page2, wx.ID_ANY,
            "TODO: replace this control with something more useful...")
        self.staticText2.Wrap(200)
        page_sizer_2.Add(self.staticText2, wx.SizerFlags().Border(wx.ALL))
        page2.SetSizerAndFit(page_sizer_2)

        page3 = wx.Panel(self.GetBookCtrl(), wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize,
            wx.TAB_TRAVERSAL)
        self.GetBookCtrl().AddPage(page3, "Page 3")

        page_sizer_3 = wx.BoxSizer(wx.VERTICAL)

        self.staticText3 = wx.StaticText(page3, wx.ID_ANY,
            "TODO: replace this control with something more useful...")
        self.staticText3.Wrap(200)
        page_sizer_3.Add(self.staticText3, wx.SizerFlags().Border(wx.ALL))
        page3.SetSizerAndFit(page_sizer_3)

        self.LayoutDialog(wx.BOTH)
# ************* End of generated code ***********
# DO NOT EDIT THIS COMMENT BLOCK!
#
# Code below this comment block will be preserved
# if the code for this class is re-generated.
# ***********************************************
