# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wxui_generated

    ${CMAKE_CURRENT_LIST_DIR}/../wxui/choicebook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/commonctrls_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/dlgmultitest_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/form_toolbar_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/import_test_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/listbook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/mainframe_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/my_images.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/notebook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/other_ctrls_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/popupwin_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/python_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/ribbondlg_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/toolbook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/treebook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../wxui/wizard_base.cpp

)
