///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/gdicmn.h>

#include <wx/bmpbndl.h>

wxImage wxueImage(const unsigned char* data, size_t size_data);

namespace wxue_img
{
    wxBitmapBundle bundle_wiztest_png();
    wxBitmapBundle bundle_wiztest2_png();

    extern const unsigned char wiztest2_png[6797];
    extern const unsigned char wiztest_png[1239];
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
