###############################################################################
# Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# Do not edit any code above the "End of generated code" comment block.
# Any changes before that block will be lost if it is re-generated!
###############################################################################

WX_GLOBAL_CONSTANTS = true unless defined? WX_GLOBAL_CONSTANTS

require 'wx/core'

$ISSUE_DLG_960 = 6000

require_relative 'images'

class DlgIssue_960 < Wx::Dialog
  attr_accessor :staticText
  def initialize(parent, id = $ISSUE_DLG_960, title =
  'C’est une bonne journée pour tester', pos =
                                            Wx::DEFAULT_POSITION, size = Wx::DEFAULT_SIZE,
                                            style = Wx::DEFAULT_DIALOG_STYLE)

    super(parent, id, title, pos, size, style)

    dlg_sizer = Wx::BoxSizer.new(Wx::VERTICAL)

    @staticText = Wx::StaticText.new(self, Wx::ID_ANY,
      'The following are bitmaps that have filenames which are invalid as C++ or Python variables. This is used to test resolution of issue #960.')
    @staticText.wrap(300)
    dlg_sizer.add(@staticText, Wx::SizerFlags.new.border(Wx::ALL))

    box_sizer = Wx::BoxSizer.new(Wx::HORIZONTAL)

    bmp = Wx::StaticBitmap.new(self, Wx::ID_ANY, wxue_get_bundle($img_1_bottom_png))
    box_sizer.add(bmp, Wx::SizerFlags.new.border(Wx::ALL))

    bmp_2 = Wx::StaticBitmap.new(self, Wx::ID_ANY, wxue_get_bundle($bottom_1__png))
    box_sizer.add(bmp_2, Wx::SizerFlags.new.border(Wx::ALL))

    dlg_sizer.add(box_sizer, Wx::SizerFlags.new.border(Wx::ALL))

    bmp_3 = Wx::StaticBitmap.new(self, Wx::ID_ANY, wxue_get_bundle($Ainsi_c3a7a_se_passe_png))
    dlg_sizer.add(bmp_3, Wx::SizerFlags.new.border(Wx::ALL))

    stdBtn = create_std_dialog_button_sizer(Wx::OK|Wx::CANCEL)
    dlg_sizer.add(create_separated_sizer(stdBtn),
      Wx::SizerFlags.new.expand.border(Wx::ALL))

    set_sizer_and_fit(dlg_sizer)
    centre(Wx::BOTH)
  end
# ************* End of generated code ***********
# DO NOT EDIT THIS COMMENT BLOCK!
#
# Code below this comment block will be preserved
# if the code for this class is re-generated.
# ***********************************************

end
