///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

// Order dependent includes
#include <wx/stattext.h>
#include <wx/generic/stattextg.h>
#include <wx/treectrl.h>
#include <wx/generic/treectlg.h>

#include <wx/animate.h>
#include <wx/calctrl.h>
#include <wx/generic/calctrlg.h>
#include <wx/collpane.h>
#include <wx/colour.h>
#include <wx/dialog.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/generic/animate.h>
#include <wx/hyperlink.h>
#include <wx/generic/hyperlink.h>
#include <wx/settings.h>

class wxGeneric;

namespace wxue_img
{
    // ../art/clr_hourglass.gif
    extern const unsigned char clr_hourglass_gif[2017];
}

class GenericControlsDialog : public wxDialog
{
public:
    static const int form_id = wxID_ANY;
    static const int form_style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER;
    static const wxPoint form_pos() { return wxDefaultPosition; }
    static const wxSize form_size() { return  wxDefaultSize; }
    static const wxString form_title() { return wxString::FromUTF8("Generic Controls Test Dialog"); }

    GenericControlsDialog() {}
    GenericControlsDialog(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Generic Controls Test Dialog",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }
    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Generic Controls Test Dialog",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr);

    // Inserted code

protected:

    // Class member variables

    wxCollapsiblePane* m_collapsible_pane;
    wxGenericAnimationCtrl* m_animation_ctrl;
    wxGenericCalendarCtrl* m_calendar;
    wxGenericHyperlinkCtrl* m_hyperlink;
    wxGenericStaticText* m_staticText;
    wxGenericTreeCtrl* m_treeCtrl;
    wxStaticText* m_staticText2;

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// ***********************************************
  // clang-format on
};
