///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/gdicmn.h>

#include <wx/bmpbndl.h>

namespace wxue_img
{
    wxImage get_image(const unsigned char* data, size_t size_data);

    wxBitmapBundle bundle_img_1_bottom_png();  // 1_bottom.png
    wxBitmapBundle bundle_Ainsi_c3a7a_se_passe_png();  // Ainsi ça se passe.png
    wxBitmapBundle bundle_bottom_1__png();  // bottom(1).png
    wxBitmapBundle bundle_debug_32_png();  // debug_32.png
    wxBitmapBundle bundle_disabled_png();  // disabled.png
    wxBitmapBundle bundle_english_png();  // english.png
    wxBitmapBundle bundle_er_png();  // er.png
    wxBitmapBundle bundle_face_smile_svg(int width, int height);
    wxBitmapBundle bundle_focus_png();  // focus.png
    wxBitmapBundle bundle_fontPicker_png();  // fontPicker.png
    wxBitmapBundle bundle_french_png();  // french.png
    wxBitmapBundle bundle_grid_svg(int width, int height);
    wxBitmapBundle bundle_japanese_png();  // japanese.png
    wxBitmapBundle bundle_left_png();  // left.png
    wxBitmapBundle bundle_no_hour_png();  // no_hour.png
    wxBitmapBundle bundle_normal_png();  // normal.png
    wxBitmapBundle bundle_re_png();  // re.png
    wxBitmapBundle bundle_ribbon_button_hybrid_png();  // ribbon_button_hybrid.png
    wxBitmapBundle bundle_toggle_button_png();  // toggle_button.png
    wxBitmapBundle bundle_wiztest_png();  // wiztest.png
    wxBitmapBundle bundle_wiztest2_png();  // wiztest2.png
    wxBitmapBundle bundle_wxNotebook_png();  // wxNotebook.png
    wxBitmapBundle bundle_wxPython_png();  // wxPython.png
    wxBitmapBundle bundle_wxPython_1_5x_png();  // wxPython_1_5x.png
    wxBitmapBundle bundle_wxPython_2x_png();  // wxPython_2x.png

    wxImage image_Ainsi_c3a7a_se_passe_png();
    wxImage image_bottom_1__png();
    wxImage image_debug_32_png();
    wxImage image_disabled_png();
    wxImage image_english_png();
    wxImage image_er_png();
    wxImage image_focus_png();
    wxImage image_fontPicker_1_25x_png();
    wxImage image_fontPicker_1_5x_png();
    wxImage image_fontPicker_1_75x_png();
    wxImage image_fontPicker_2x_png();
    wxImage image_fontPicker_png();
    wxImage image_french_png();
    wxImage image_img_1_bottom_png();
    wxImage image_japanese_png();
    wxImage image_left_png();
    wxImage image_no_hour_png();
    wxImage image_normal_png();
    wxImage image_re_png();
    wxImage image_ribbon_button_hybrid_png();
    wxImage image_toggle_button_png();
    wxImage image_wiztest2_png();
    wxImage image_wiztest_png();
    wxImage image_wxNotebook_png();
    wxImage image_wxPython_1_5x_png();
    wxImage image_wxPython_2x_png();
    wxImage image_wxPython_png();
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
