///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/event.h>
#include <wx/frame.h>
#include <wx/gdicmn.h>
#include <wx/statusbr.h>
#include <wx/toolbar.h>

class MainFrameBase : public wxFrame
{
public:
    MainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = "wxUiTesting",
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500, 300),
        long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL);

protected:

    // Virtual event handlers -- override them in your derived class

    virtual void OnChoicebook(wxCommandEvent& event) { event.Skip(); }
    virtual void OnCommonDialog(wxCommandEvent& event) { event.Skip(); }
    virtual void OnImportTest(wxCommandEvent& event) { event.Skip(); }
    virtual void OnListbook(wxCommandEvent& event) { event.Skip(); }
    virtual void OnMultiTestDialog(wxCommandEvent& event) { event.Skip(); }
    virtual void OnNotebook(wxCommandEvent& event) { event.Skip(); }
    virtual void OnOtherCtrls(wxCommandEvent& event) { event.Skip(); }
    virtual void OnPythonDlg(wxCommandEvent& event) { event.Skip(); }
    virtual void OnQuit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnRibbonDialog(wxCommandEvent& event) { event.Skip(); }
    virtual void OnToolbook(wxCommandEvent& event) { event.Skip(); }
    virtual void OnTreebook(wxCommandEvent& event) { event.Skip(); }
    virtual void OnWizard(wxCommandEvent& event) { event.Skip(); }

    // Class member variables

    wxStatusBar* m_statusBar;
    wxToolBar* m_toolBar;
};

namespace wxue_img
{
    // Images declared in this class module:

    extern const unsigned char wxPython_1_5x_png[765];
    extern const unsigned char wxPython_2x_png[251];
    extern const unsigned char wxPython_png[399];
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
