# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wxui_generated

    ${CMAKE_CURRENT_LIST_DIR}/choicebook.cpp
    ${CMAKE_CURRENT_LIST_DIR}/commonctrls_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/dlgmultitest_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/form_toolbar_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/import_test_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/listbook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/mainframe_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/my_images.cpp
    ${CMAKE_CURRENT_LIST_DIR}/notebook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/other_ctrls_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/popupwin_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/python_dlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbondlg_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/toolbook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/treebook_base.cpp
    ${CMAKE_CURRENT_LIST_DIR}/wizard_base.cpp

)
