///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#include "normal_frame.h"

bool NormalFrame::Create(wxWindow* parent, wxWindowID id, const wxString& title,
    const wxPoint& pos, const wxSize& size, long style, const wxString &name)
{

    if (!wxFrame::Create(parent, id, title, pos, size, style, name))
    {
        return false;
    }
    if (pos != wxDefaultPosition || size != wxDefaultSize)
    {
        SetSize(FromDIP(pos).x, FromDIP(pos).y,
        FromDIP(size).x, FromDIP(size).y, wxSIZE_USE_EXISTING);
    }

    m_toolBar = CreateToolBar();
    m_toolBar->Realize();

    m_menubar = new wxMenuBar();

    SetMenuBar(m_menubar);

    m_statusBar = CreateStatusBar();

    Centre(wxBOTH);

    return true;
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
