//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: Crafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _SRC_IMPORTS_CRAFTER_BASE_CLASSES_HPP
#define _SRC_IMPORTS_CRAFTER_BASE_CLASSES_HPP

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/panel.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/aui/auibook.h>
#include <wx/imaglist.h>
#include <wx/gbsizer.h>
#include <wx/infobar.h>
#include <wx/radiobox.h>
#include <wx/collpane.h>
#include <wx/stattext.h>
#include <wx/statbmp.h>
#include <wx/textctrl.h>
#include <wx/choice.h>
#include <wx/arrstr.h>
#include <wx/slider.h>
#include <wx/propgrid/manager.h>
#include <wx/propgrid/property.h>
#include <wx/propgrid/advprops.h>
#include <wx/grid.h>
#include <wx/ribbon/bar.h>
#include <wx/ribbon/art.h>
#include <wx/ribbon/page.h>
#include <wx/ribbon/panel.h>
#include <wx/ribbon/toolbar.h>
#include <wx/ribbon/buttonbar.h>
#include <wx/ribbon/gallery.h>
#include <wx/tglbtn.h>
#include <wx/button.h>
#include <wx/srchctrl.h>
#include <wx/clrpicker.h>
#include <wx/spinctrl.h>
#include <wx/hyperlink.h>
#include <wx/mstream.h>
#include <wx/filename.h>
#include <wx/animate.h>
#include <wx/statbox.h>
#include <wx/richtext/richtextctrl.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class CrafterBase : public wxPanel
{
protected:
    wxAuiNotebook* m_auinotebook1;
    wxPanel* m_panel1;
    wxInfoBar* m_infoCtrl1;
    wxRadioBox* m_radioBox1;
    wxCollapsiblePane* m_collPane4;
    wxStaticText* m_staticText10;
    wxStaticBitmap* m_bitmap2;
    wxTextCtrl* m_textCtrlWithValidator;
    wxChoice* m_choice1;
    wxStaticBitmap* m_bitmap21;
    wxSlider* m_slider1;
    wxPanel* m_panel12;
    wxPropertyGridManager* m_propertyGridManager1;
    wxPGProperty* m_propertyGridItem1;
    wxPGProperty* m_propertyGridItem2;
    wxGrid* m_grid1;
    wxRibbonBar* m_ribbonBar1;
    wxRibbonPage* m_ribbonPage1;
    wxRibbonPanel* m_ribbonPanel1;
    wxRibbonToolBar* m_ribbonToolBar1;
    wxRibbonPanel* m_ribbonPanel2;
    wxRibbonButtonBar* m_ribbonButtonBar1;
    wxRibbonPanel* m_ribbonPanel3;
    wxRibbonGallery* m_ribbonGallery62;
    wxPanel* m_panel3;
    wxToggleButton* m_toggleBtn1;
    wxSearchCtrl* m_searchCtrl1;
    wxColourPickerCtrl* m_colourPicker1;
    wxSpinCtrl* m_spinCtrl1;
    wxHyperlinkCtrl* m_hyperlink1;
    wxAnimationCtrl* m_animCtrl1;
    wxRichTextCtrl* m_richText1;

protected:

public:
    wxInfoBar* GetInfoCtrl1() { return m_infoCtrl1; }
    wxRadioBox* GetRadioBox1() { return m_radioBox1; }
    wxStaticText* GetStaticText10() { return m_staticText10; }
    wxStaticBitmap* GetBitmap2() { return m_bitmap2; }
    wxCollapsiblePane* GetCollPane4() { return m_collPane4; }
    wxTextCtrl* GetTextCtrlWithValidator() { return m_textCtrlWithValidator; }
    wxChoice* GetChoice1() { return m_choice1; }
    wxStaticBitmap* GetBitmap21() { return m_bitmap21; }
    wxSlider* GetSlider1() { return m_slider1; }
    wxPanel* GetPanel1() { return m_panel1; }
    wxPropertyGridManager* GetPropertyGridManager1() { return m_propertyGridManager1; }
    wxGrid* GetGrid1() { return m_grid1; }
    wxRibbonBar* GetRibbonBar1() { return m_ribbonBar1; }
    wxPanel* GetPanel12() { return m_panel12; }
    wxToggleButton* GetToggleBtn1() { return m_toggleBtn1; }
    wxSearchCtrl* GetSearchCtrl1() { return m_searchCtrl1; }
    wxColourPickerCtrl* GetColourPicker1() { return m_colourPicker1; }
    wxSpinCtrl* GetSpinCtrl1() { return m_spinCtrl1; }
    wxHyperlinkCtrl* GetHyperlink1() { return m_hyperlink1; }
    wxAnimationCtrl* GetAnimCtrl1() { return m_animCtrl1; }
    wxRichTextCtrl* GetRichText1() { return m_richText1; }
    wxPanel* GetPanel3() { return m_panel3; }
    wxAuiNotebook* GetAuinotebook1() { return m_auinotebook1; }
    CrafterBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxTAB_TRAVERSAL);
    virtual ~CrafterBase();
};

#endif
