////////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
//
// DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <wx/animate.h>
#include <wx/aui/auibook.h>
#include <wx/bitmap.h>
#include <wx/choice.h>
#include <wx/clrpicker.h>
#include <wx/collpane.h>
#include <wx/colour.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/grid.h>
#include <wx/hyperlink.h>
#include <wx/icon.h>
#include <wx/image.h>
#include <wx/infobar.h>
#include <wx/intl.h>
#include <wx/panel.h>
#include <wx/propgrid/advprops.h>
#include <wx/propgrid/manager.h>
#include <wx/propgrid/propgrid.h>
#include <wx/radiobox.h>
#include <wx/ribbon/art.h>
#include <wx/ribbon/bar.h>
#include <wx/ribbon/control.h>
#include <wx/ribbon/toolbar.h>
#include <wx/richtext/richtextctrl.h>
#include <wx/settings.h>
#include <wx/slider.h>
#include <wx/spinctrl.h>
#include <wx/srchctrl.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/tglbtn.h>

class ImportCrafterBase : public wxPanel
{
public:
    wxAuiNotebook* m_auinotebook1;
    wxInfoBar* m_infoCtrl1;

    ImportCrafterBase() {}
    ImportCrafterBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500, 300),
        long style = wxTAB_TRAVERSAL, const wxString &name = wxPanelNameStr)
    {
        Create(parent, id, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500, 300),
        long style = wxTAB_TRAVERSAL, const wxString &name = wxPanelNameStr);

protected:

    // Class member variables

    wxAnimationCtrl* m_animCtrl1;
    wxChoice* m_choice1;
    wxCollapsiblePane* m_collPane4;
    wxColourPickerCtrl* m_colourPicker1;
    wxGrid* m_grid1;
    wxHyperlinkCtrl* m_hyperlink1;
    wxPGProperty* m_propertyGridItem1;
    wxPGProperty* m_propertyGridItem2;
    wxPropertyGridManager* m_propertyGridManager1;
    wxPropertyGridPage* m_propertyGridPage;
    wxRadioBox* m_radioBox1;
    wxRibbonBar* m_ribbonBar1;
    wxRichTextCtrl* m_richText1;
    wxSearchCtrl* m_searchCtrl1;
    wxSlider* m_slider1;
    wxSpinCtrl* m_spinCtrl1;
    wxStaticText* m_staticText10;
    wxTextCtrl* m_textCtrlWithValidator;
    wxToggleButton* m_toggleBtn1;
};

namespace wxue_img
{
    // Images declared in this class module:

    extern const unsigned char clr_hourglass_gif[2017];
    extern const unsigned char french_png[252];
    extern const unsigned char redo_png[945];
    extern const unsigned char ribbon_button_hybrid_png[192];
    extern const unsigned char toggle_button_png[277];
    extern const unsigned char undo_png[962];
}
