# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wxue_generated_code

    ${CMAKE_CURRENT_LIST_DIR}/cpp/aui_frame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/mdi_frame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/normal_frame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/cpp/sdi_frame.cpp

)
