///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#pragma once

#include <wx/dataview.h>
#include <wx/dialog.h>
#include <wx/event.h>
#include <wx/font.h>
#include <wx/gdicmn.h>
#include <wx/grid.h>
#include <wx/listbox.h>
#include <wx/notebook.h>
#include <wx/propgrid/propgrid.h>
#include <wx/stattext.h>
#include <wx/treectrl.h>
#include <wx/treelist.h>

class DataDlg : public wxDialog
{
public:
    DataDlg() {}
    DataDlg(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Data testing", const wxPoint& pos =
        wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }
    bool Create(wxWindow *parent, wxWindowID id = wxID_ANY, const wxString& title = "Data testing", const wxPoint& pos =
        wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER, const wxString &name = wxDialogNameStr);

    void OnEventName(const std::string& event_name);

protected:

    // Event handlers

    void OnChanged(wxPropertyGridEvent& event);
    void OnClearList(wxCommandEvent& event);
    void OnColumnResize(wxGridSizeEvent& event);
    void OnDataViewCtrlSelectionChanged(wxDataViewEvent& event);
    void OnGridSize(wxSizeEvent& event);
    void OnInit(wxInitDialogEvent& event);
    void OnSelected(wxPropertyGridEvent& event);
    void OnTreeItemExpanded(wxTreeEvent& event);
    void OnTreeListSelChanged(wxTreeListEvent& event);

    // Class member variables

    wxDataViewColumn* m_data_view_column2;
    wxDataViewColumn* m_data_view_column;
    wxDataViewColumn* m_data_view_list_column2;
    wxDataViewColumn* m_data_view_list_column;
    wxDataViewCtrl* m_data_view_ctrl;
    wxDataViewListCtrl* m_data_view_list_ctrl;
    wxDataViewTreeCtrl* m_data_view_tree_ctrl;
    wxGrid* m_kicadGrid;  // Grid imported from a kicad dialog, utilizing column sizes and labels
    wxListBox* m_events_list;
    wxNotebook* m_notebook;
    wxPGProperty* m_pgi_integer;
    wxPGProperty* m_pgi_string;
    wxPGProperty* m_propertyGridICategory;
    wxPropertyGrid* m_propertyGrid;
    wxStaticText* m_static_text2;
    wxStaticText* m_static_text4;
    wxStaticText* m_static_text5;
    wxStaticText* m_static_text;
    wxTreeCtrl* m_tree_ctrl;
    wxTreeListCtrl* m_tree_list_ctrl;
};

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
