///////////////////////////////////////////////////////////////////////////////
// Code generated by wxUiEditor - see https://github.com/KeyWorksRW/wxUiEditor/
//
// Do not edit any code above the "End of generated code" comment block.
// Any changes before that block will be lost if it is re-generated!
///////////////////////////////////////////////////////////////////////////////

// clang-format off

#include <wx/ribbon/page.h>
#include <wx/ribbon/panel.h>

#include "images.h"

#include "form_ribbonbar_tool.h"

RibbonBarTool::RibbonBarTool(wxWindow* parent, wxWindowID id, const wxPoint& pos, const wxSize& size, long style)
     : wxRibbonBar(parent, id, pos, size, style)
{
    SetArtProvider(new wxRibbonDefaultArtProvider);

    auto* rbnPage = new wxRibbonPage(this, wxID_ANY, "Page 1");

    auto* rbnPanel = new wxRibbonPanel(rbnPage, wxID_ANY, "Page 1, panel 1");

    auto* rbnToolBar = new wxRibbonToolBar(rbnPanel, wxID_ANY);
    {
        rbnToolBar->AddTool(tool1,
            wxue_img::bundle_face_smile_svg(FromDIP(24), FromDIP(24)).GetBitmap(wxDefaultSize), wxEmptyString,
            wxRIBBON_BUTTON_NORMAL);
    }
    rbnToolBar->Realize();

    Realize();
}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
